# Generated by Django 3.2.8 on 2021-10-23 19:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='projects',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='screenshot'),
        ),
    ]
