# Generated by Django 3.2.8 on 2021-10-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0003_auto_20211023_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='main_technology_used',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
