# Generated by Django 3.2.8 on 2021-10-24 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awward', '0004_projects_main_technology_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Unlikeable'), (2, '2 - Horrible'), (3, '3 - Hmmmm'), (4, '4 - Bad'), (5, '5 - Fine'), (6, '6 - Good'), (7, '7 - Very Good'), (8, '8 - Likeable'), (9, '9 - Perfect'), (10, '10 - Awesome')])),
                ('usability_rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Unlikeable'), (2, '2 - Horrible'), (3, '3 - Hmmmm'), (4, '4 - Bad'), (5, '5 - Fine'), (6, '6 - Good'), (7, '7 - Very Good'), (8, '8 - Likeable'), (9, '9 - Perfect'), (10, '10 - Awesome')])),
                ('content_rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Unlikeable'), (2, '2 - Horrible'), (3, '3 - Hmmmm'), (4, '4 - Bad'), (5, '5 - Fine'), (6, '6 - Good'), (7, '7 - Very Good'), (8, '8 - Likeable'), (9, '9 - Perfect'), (10, '10 - Awesome')])),
                ('review', models.TextField(blank=True, max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awward.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
